package psp.user.model;

public enum EPermission {

    DELETE_DISCUSSION,
    DELETE_POST_COMMENT,
    REPORT_POST_ABUSE,
    REPORT_DISCUSSION_ABUSE,
    CREATE_DISCUSSION,
    CLOSE_DISCUSSION,
    VIEW_USER_DATA,
    LIST_USERS,
    START_CHAT,
    SUSPEND_USER_ACCOUNT,
    MANAGE_ROLES_PERMISSIONS,
    DELETE_USER_ACCOUNT

}
